### PR TITLE
Solves issue 29 and 31

### LINKED ISSUE #29: Syntax highlighting broken for values that contain negative integers.
screen shot 2015-06-27 at 11 35 31

Specs:
Atom 1.0
language-css 0.32.0
Mac OS X 10.9

### LINKED ISSUE #31: Syntax highlighting broken for some attribute selectors
See the screenshot below.

screen shot 2015-06-29 at 12 21 16 pm

The code in the screenshot confuses the syntax highlighter:

```CSS
[disabled],
[disabled] + p {
    /* styles */
}
```

### PR DESCRIPTION
**Pull request by burodepeper**
Fixes #29 
Fixes #31

### CODE REVIEW

File: spec/css-spec.coffee [hunk 1]
```diff
@@ -20,6 +20,19 @@ describe 'CSS grammar', ->
       expect(tokens[8]).toEqual value: ';', scopes: ['source.css', 'meta.property-list.css', 'meta.property-value.css', 'punctuation.terminator.rule.css']
       expect(tokens[10]).toEqual value: '}', scopes: ['source.css', 'meta.property-list.css', 'punctuation.section.property-list.end.css']
 
+    # Needs more complex examples
```
Comment (50Wliu) [inline spec/css-spec.coffee]: What more complex examples are needed?  Any chance you can add them onto this PR?

Comment (burodepeper) [inline spec/css-spec.coffee]: While looking through the css specs on MDN, I vaguely remember (consider that this is a while ago) seeing things that simply weren't specced in language-css. I have looked into them, but for some reason (remember, this is a while ago) that led to rewriting a bigger part of the grammar which I deemed a bit out of the scope of a simple fix for an issue.

**Comment by 50Wliu** [comment]
The number grammar should make sure it isn't preceded by a word for a more robust fix.

**Comment by burodepeper** [comment]
Could you be a bit more specific? As far as I can see, I've merely added some missing attribute-values.

**Comment by 50Wliu** [comment]
Yes, but #29 if about numbers getting improperly matched in attribute values.  To prevent that from happening again the number regex should make sure that it isn't preceded by a word.

File: grammars/css.cson [hunk 2]
```diff
@@ -333,7 +333,11 @@
         'captures':
           '1':
             'name': 'keyword.other.unit.css'
-        'match': '(?x)\n\t\t\t\t\t    (?:-|\\+)?(?:(?:[0-9]+(?:\\.[0-9]+)?)|(?:\\.[0-9]+))\n\t\t\t\t\t    ((?:px|pt|ch|cm|mm|in|r?em|ex|pc|deg|g?rad|dpi|dpcm|dppx|fr|ms|s|turn|vh|vmax|vmin|vw)\\b|%)?\n\t\t\t\t\t'
+        # NOTE by @burodepeper
+        # I have no idea what the stuff in the regex was intended to do that I removed, but it doesn't seem to break anything either way. I've left the original here, just in case.
+        # Tests are still fine, and a manual inspection of a rather large css file didn't show anything gone bad.
+        # 'match': '(?x)\n\t\t\t\t\t    (?:-|\\+)?(?:(?:[0-9]+(?:\\.[0-9]+)?)|(?:\\.[0-9]+))\n\t\t\t\t\t    ((?:px|pt|ch|cm|mm|in|r?em|ex|pc|deg|g?rad|dpi|dpcm|dppx|fr|ms|s|turn|vh|vmax|vmin|vw)\\b|%)?\n\t\t\t\t\t'
```
Comment (MaximSokolov) [inline grammars/css.cson]: (?x) permits whitespaces in pattern, so you can replace `\n`, `\t` with actual newlines, tabs. It was broken by language converter.
Refs: atom/apm#467

Comment (burodepeper) [inline grammars/css.cson]: So it is safe to remove?

Comment (MaximSokolov) [inline grammars/css.cson]: Yes, you can remove them. But it would be better if you replace escape sequences with tabs and whitespaces for readability (like it was before converting).

Comment (burodepeper) [inline grammars/css.cson]: I think I'm completely missing the point here ; )
What readability are we talking about?
`(?x)\n\t\t\t\t\t    ` is pretty much complete non-sense to have in a match as far as I can tell...

Comment (MaximSokolov) [inline grammars/css.cson]: It was broken:
```coffee
'match': '(?x)\n\ttest'
```
should be
```coffee
'match': '(?x)
  test
'
```

Comment (burodepeper) [inline grammars/css.cson]: Ah, I finally get what you mean. Fixed it.

File: grammars/css.cson [hunk 3]
```diff
@@ -333,7 +333,10 @@
         'captures':
           '1':
             'name': 'keyword.other.unit.css'
-        'match': '(?x)\n\t\t\t\t\t    (?:-|\\+)?(?:(?:[0-9]+(?:\\.[0-9]+)?)|(?:\\.[0-9]+))\n\t\t\t\t\t    ((?:px|pt|ch|cm|mm|in|r?em|ex|pc|deg|g?rad|dpi|dpcm|dppx|fr|ms|s|turn|vh|vmax|vmin|vw)\\b|%)?\n\t\t\t\t\t'
+        'match': '(?x)
```
Comment (50Wliu) [inline grammars/css.cson]: This should be triple-quoted, not sure why Travis is passing:
```cson
'match': '''
(?x)
stuff
'''
```

File: spec/css-spec.coffee [hunk 4]
```diff
@@ -20,6 +20,32 @@ describe 'CSS grammar', ->
...
+      expect(tokens[6]).toEqual value: ']', scopes: ["source.css", "meta.selector.css", "meta.attribute-selector.css", "punctuation.definition.entity.css"]
+      expect(tokens[7]).toEqual value: ' + ', scopes: ["source.css", "meta.selector.css"]
+      expect(tokens[8]).toEqual value: 'p', scopes: ["source.css", "meta.selector.css", "entity.name.tag.css"]
+
+    it 'tokenizes correct numeric values', ->
+      {tokens} = grammar.tokenizeLine 'div { font-size: 14px; }'
+      expect(tokens[7]).toEqual value: '14', scopes: ['source.css', 'meta.property-list.css', 'meta.property-value.css', 'constant.numeric.css']
+      expect(tokens[8]).toEqual value: 'px', scopes: ['source.css', 'meta.property-list.css', 'meta.property-value.css', 'constant.numeric.css', 'keyword.other.unit.css']
+
+    it 'doesn\'t tokenize incorrect numeric values (1)', ->
```
Comment (50Wliu) [inline spec/css-spec.coffee]: Small nit: To prevent escaping I would just switch the single quotes to double quotes.  Your call though.

File: grammars/css.cson (hunk 3 above)
Comment (burodepeper) [inline grammars/css.cson]: Ok, changed.

Comment (MaximSokolov) [inline grammars/css.cson]: > This should be triple-quoted

Not necessary. `(?x)` will remove all `\n`, `\t` anyway.

File: spec/css-spec.coffee (hunk 4 above)
Comment (burodepeper) [inline spec/css-spec.coffee]: Ha, I knew someone would mention that. I like my string single quoted though. Personal preference.

File: grammars/css.cson (hunk 3 above)
Comment (burodepeper) [inline grammars/css.cson]: Oh, not changed anymore.

Comment (50Wliu) [inline grammars/css.cson]: :scream: Why did Travis fail when I did that then? :P

Comment (burodepeper) [inline grammars/css.cson]: Blame Jasmine ; )

**Comment by 50Wliu** [comment]
:zap:

**Comment by burodepeper** [comment]
:+1:



—David van Gemeren

+31 (0)6 47 838 561

www.burodepeper.nl
